committing changes

diff --git a/wso2-is-bosh-release/jobs/wso2is/templates/ctl.erb b/wso2-is-bosh-release/jobs/wso2is/templates/ctl.erb
--- a/wso2-is-bosh-release/jobs/wso2is/templates/ctl.erb
+++ b/wso2-is-bosh-release/jobs/wso2is/templates/ctl.erb
@@ -92,6 +92,19 @@ case $1 in
     # driver_file=`ls postgres*.jar`
     # cp ${driver_file} ${WSO2_IS_HOME}/lib
 
+export local_docker_ip=$(ip route get 1 | awk '{print $NF;exit}')
+   axi2_xml_location=${WSO2_IS_HOME}/repository/conf/axis2/axis2.xml
+if [[ ! -z ${local_docker_ip} ]]; then
+   sed -i "s#<parameter\ name=\"localMemberHost\".*#<parameter\ name=\"localMemberHost\">${local_docker_ip}<\/parameter>#" "${axi2_xml_location}"
+   if [[ $? == 0 ]]; then
+      echo "Successfully updated localMemberHost with ${local_docker_ip}"
+   else
+      echo "Error occurred while updating localMemberHost with ${local_docker_ip}"
+   fi
+fi
+
+
+
     $WSO2_IS_HOME/bin/wso2server.sh start
 
     # Sleep for a little while so the server comes up
